AnubisLMS/Anubis

api/anubis/config.py

Two `self.SQLALCHEMY_DATABASE_URI` assignment are written. The redundant one is removed.

Remove redundant DATABASE_URI assignment

---

api/Makefile
web/.eslintrc.yml
web/src/Components/Public/Assignments/AssignmentCard.jsx
web/src/Pages/Admin/Assignment/Assignment.jsx
web/src/Pages/Public/Assignments.jsx

This PR resolves #133.
In this PR I added 5 second polling for 60 seconds whenever a user clicks on the `Create Repo` button in an AssignmentCard. While this polling is happening, a progress circle will appear over the disabled IDE button and polling to the assignments endpoint will happen in the background. Each polling check, it will assert that for all assignments the `has_repo` value has not changed. If it has changed, then it will reset the assignments value and end the polling.
This wasn't very easy to test so it may require some more eyes before merging, but I think it covers the core of what needs to happen here.
I also cleaned up some styling in the card to make it a bit more consistent with how you use flexbox.
It may be a bit nicer to review with whitespace changes off.

CHG add polling to assignments so ide button works when repo link active

---

web/src/Components/Public/Assignments/AssignmentCard.jsx
web/src/Pages/Public/Assignments.jsx

In my PR last night I added polling to the assignments to wait for the github repo to be created when `create repo` is clicked. What I had forgotten was that, if there were several assignments each one would appear as loading while we await the successful repo creation. 
This fix lets us keep track of the current polling assignment's ID so that we keep track of only one specific has repo value and only one assignment card shows up as loading when we are polling.
I tested this by allowing any assignment to be set to polling and then if it has a repo the polling should end after 5 seconds. If it doesn't it should await that cards repo url.

FIX potential issue with polling

---

api/anubis/models/__init__.py
api/anubis/utils/lms/courses.py

This PR fixes the `whoami` bug mentioned in #115 . Now when we access `/api/public/auth/whoami`, specifically when we access `User.data` property:
- The `professor_for` field lists the  courses the user is a professor for
- The `ta_for` field lists the courses the user is either a professor or a ta for
- The `admin_for` field is the union of `ta_for` and `professor_for`
Some of the issues that happened or discovered when I was coding this new logic:
- The original plan mentioned by @wabscale in #115 , which is to add this logic under `api/anubis/utils/lms/courses.py`, does not work because it will introduce cyclic association and I don't think it fits into any other places. So I just add it as a property under the `User` model.
- I attempted to separate each model into its own file but …

Fix whoami bug

---

k8s/prod/Makefile
k8s/prod/mariadb-values.yaml

One issue that Anubis has suffered from in the past is it's single leader database. When the main database container kicks over for whatever reason (issues on the node, networking, etc...) everything else comes crashing down.
This is why we are now going to be using mariadb galera. Galera is the mutli-leader version of mariadb. I have used it extensively in the past and it seems pretty resilient. We'll start with 2 mariadb replicas, and scale them up as needed.
This PR replaces the old single node mariadb to mutli-leader galera.

CHG mariadb galera

---

api/anubis/config.py
api/anubis/utils/lms/theia.py
docker-compose.yml
k8s/chart/templates/api.yml
k8s/chart/templates/ingress.yml
k8s/chart/templates/rpc.yml
k8s/chart/values.yaml
k8s/debug/provision.sh
k8s/prod/Makefile
theia/ide/xv6/Dockerfile
theia/proxy/index.js

We will need to figure out how to configure theia to run on a different base url path. Something like `anubis.osiris.services/ide/proxy` would probably work fine.
We would probably then need to configure the theia builds [here](https://github.com/GusSand/Anubis/blob/ac364d6708b9ec4cbf6ae6c0f24474e25dc05145/theia/ide/xv6/latest.package.json) and [here](https://github.com/GusSand/Anubis/blob/ac364d6708b9ec4cbf6ae6c0f24474e25dc05145/theia/ide/xv6/latest.package.json). Then we would need to remove the [THEIA_DOMAIN](https://github.com/GusSand/Anubis/blob/ac364d6708b9ec4cbf6ae6c0f24474e25dc05145/api/anubis/config.py#L42) config, and replace it with something like `DOMAIN`.
Then quite seperately we would need to change the theia proxy [IngressRoute](https://github.com/GusSand/Anubis/blob/ac364d6 …

CHG same domain theia

---

theia/ide/jepst/Dockerfile
theia/init/entrypoint.sh

Commands echoed to student bashrc were going to the copy in /etc, not the student's home directory

FIX jepst Dockerfile bashrc to right place

---

web/src/Pages/Public/Lectures.jsx

Remove debug code that prints `lectures` to the console.

RM debug code in Lectures.jsx

---

k8s/debug/provision.sh

Line 24 in `k8s/debug/provision.sh` will not work in bash as bash does not support floating-point calculations. I changed that line and now the calculation is done using `bc`.

FIX Floating-point calculation in provision.sh

---

api/anubis/config.py
api/anubis/utils/auth/oauth.py
api/anubis/views/public/__init__.py
api/anubis/views/public/auth.py
k8s/chart/templates/api.yml

This PR is the result of discussions in #240 . It's currently a work in progress. Details of this PR will be explained once all the changes I planned are committed and pushed.
A reminder to @nysteo is that in this PR the `Profile` page in front-end will be modified. Specifically the `Github Username` input box will likely be changed into a button that guides students to github authentication page.

ADD Github SSO for linking github account

---

api/jobs/bot.py

The !report command only needs to list each course once; this PR just removes the second instance of listing every course.

CHG cut report in half by only listing courses once

---

api/jobs/bot.py

Because the constructor uses `**kwargs`, no run-time error was raised. This is found with mypy using the stubs for discord.py.
[See also](https://github.com/Rapptz/discord.py/blob/9a61a5a0630f54a2365a11c110890c6952c88380/discord/embeds.py#L177-L187)

FIX correctly set the author of the embed content

---

api/.dockerignore
api/.gitignore
api/Makefile
api/requirements/dev.in
api/requirements/dev.txt
api/tests/test.sh

This allows us to run `tests/test.sh` to generate a test coverage report using [coverage.py](https://coverage.readthedocs.io/en/6.2/index.html) with pytest.
The report can be generated with `make coverage` under `api`.
An example of the report:
```
Name                                        Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------
anubis/__init__.py                              0      0   100%
anubis/app.py                                  32     28    12%   11-22, 34-52, 64-77
anubis/views/super/__init__.py                  7      7     0%   1-13
anubis/views/super/config.py                   29     29     0%   1-73
anubis/views/super/ide.py                      64     64     0%   1-114
anubis/views/super/playgrounds.py …
```

ADD Generate Test Coverage Report for the API server

---

web/src/Pages/Public/Submission/Submission.styles.jsx

Before (note that we have scrolled to the top already):
After:

FIX container overflow for long contents

---

theia/ide/theia-base/cli/anubis/assignment/utils.py
theia/ide/theia-base/cli/tests/test_utils.py
web/src/components/core/SubmissionTestExpanded/SubmissionTestExpanded.jsx

This fixes the following bugs:
- When a mismatch occurs and one input is shorter than another, the remaining lines in the longer input will be discarded while the context might not have reached the desired number of lines (having 1 line instead of 5 for example).
- Newlines are not added to the output generated.
- Fix the confusion between the expected and actual output (the tooltip showed Actual / Expected while the expected output appears in the left)
It also removes an unused log message.

FIX diff to generate the correct context for short inputs and append newlines to the output

---

.github/workflows/test-autograde-cli.yml
api/anubis/utils/testing/diffs.py
api/anubis/utils/testing/seed.py
theia/ide/theia-base/cli/anubis/assignment/utils.py
theia/ide/theia-base/cli/requirements.txt
theia/ide/theia-base/cli/tests/test_utils.py

- Increases the default context length (so the students can see a fuller diff in most cases)
- Avoid using a wrapper function in the loop for better performance

CHG use longer context for the diff produced

---

web/src/components/core/AssignmentItem/AssignmentItem.jsx
web/src/pages/core/public/Course/Course.jsx

A visible_to_students variable was added to Course.jsx to ensure that the visibility shows up correctly under an AssignmentItem component. A tooltip was added for visible assignments under AssignmentItem.jsx

ADD visible_to_students field in Course.jsx, FIX tooltip feature for assignments that are visible to students

---

web/src/components/shared/DeviceWarning.jsx

Solves #285.
The device warning shown for the iPadOS browser is disabled, by detecting the device with the flag `isTablet` using package `react-device-detect`.
Notice a change from `isBrowser` to `isDesktop`, in which the latter is preferred over `isBrowser` ([source](https://github.com/duskload/react-device-detect/blob/ec3cdbfd410f1e8dd7272fb2f131eb8bdec43ec2/docs/selectors.md))

FIX disable warning msg on iPadOS browser

---

theia/sidecar/app.py

This allows the student to force push or push without generating a commit
via the CLI without using their own credentials. Making `git push` and
`git push -f` available should be sufficient for students to maneuver with
Git on our IDE instances for the purposes of learning VCS.
It's unlikely that we are going to support more arguments without going into the depth
of actually figuring out a way to keep students authenticated and use git directly.
Allowing the students to push via Anubis CLI is only for the convenience
of not requiring them to enter a GitHub token everytime they push or
storing their SSH keys on the server if they decide to use Git in the IDE.
This is manually tested locally by invoking the added API via the CLI.

ADD sidecar API support to (force) push changes without committing.

---

web/src/components/core/Questions/Questions.jsx

The "oh no!" message suggests an error, but the absence of questions on an assignment is not an error.

FIX remove "oh no" when there are no questions

---

.github/workflows/pull-request.yml
api/anubis/lms/submissions.py
api/anubis/views/public/webhook.py
api/tests/test_assignments_admin.py

This also modifies a reaper job to get that fixed. One instance of this error would be [this](https://anubis-lms.io/courses/assignments/submissions?courseId=e271a4bc-8b5e-43eb-b2b2-15e922b8fa29&userId=3aef2252-d848-4a3e-b701-262b47127000). The student does not have late exceptions, while having a late submission, but that submission gets accepted anyway.

FIX do not mark late submissions for autograde disabled assignments as accepted

---

.github/workflows/pull-request.yml
web/Dockerfile
web/src/components/shared/DeviceWarning.jsx

The new Edge works just as fine as Firefox and Chrome.

ADD edge to compatible browsers

---

Makefile
api/Makefile
web/Makefile

Added clean target to makefile. It removes node_modules and venv

ADD make clean
