README.md

FIX logo image url in readme

---

web/src/Components/Public/Assignments/AssignmentCard.jsx
web/src/Pages/Public/Assignments.jsx

ADD dialog with description

---

theia/ide/admin/Dockerfile
theia/ide/admin/motd.txt

```
_                _     _
/ \   _ __  _   _| |__ (_)___
/ _ \ | '_ \| | | | '_ \| / __|
/ ___ \| | | | |_| | |_) | \__ \
/_/   \_|_| |_|\__,_|_.__/|_|___/
- Remember, this Cloud IDE server is temporary!
Make sure that your work is getting pushed to
github. When the session is ended, everything
(including your work) will be deleted.
- If you did not disable autosave, then every 5
minutes your work will be pushed to github.
- Use the autosave command to manually trigger
an autosave.
- Try out the anubis cli! Type: anubis --help
```

ADD motd to management ide

---

.github/workflows/test-api.yml
.github/workflows/test-web.yml
api/anubis/app.py
api/anubis/config.py
api/anubis/utils/lms/courses.py
api/anubis/utils/services/cache.py
api/anubis/utils/services/rpc.py
api/anubis/views/public/webhook.py
api/dev.py
api/tests/mintest.sh
api/tests/test.sh
api/tests/test_visuals_admin.py
api/tests/test_webhook_public.py
api/tests/utils.py
web/src/setupProxy.js

Fix issues with tests

---

Makefile
docs/development_guide.md
web/Makefile
web/src/App.jsx
web/src/Components/Navigation/Nav.jsx

Add GitHub button

---

api/anubis/models/__init__.py
api/anubis/utils/services/github.py
api/jobs/reaper.py

FIX github commit query hardcode

---

README.md

FIX image paths in readme

---

k8s/prod/Makefile
k8s/prod/filebeat-values.yaml
k8s/prod/mariadb-values.yaml

FIX some issues that came up while resetting prod

---

api/anubis/utils/lms/questions.py
api/anubis/views/admin/assignments.py
api/anubis/views/admin/questions.py
api/docker-entrypoint.sh
web/Dockerfile
web/public/index.html
web/src/Components/Admin/Assignment/QuestionControls.jsx
web/src/Pages/Admin/Autograde/Results.jsx

ADD export assignment questions functions and views

---

api/anubis/models/__init__.py
api/anubis/rpc/seed.py
api/anubis/views/admin/courses.py
api/migrations/versions/49d73a536492_chg_rename_professor_to_professor_for_.py
web/src/Components/Public/Courses/CourseCard.jsx
web/src/Pages/Admin/Course.jsx

This PR is the result of discussion in #164. I changed every place I can think of that accesses this column or field. Please take a look and see if I missed something.

CHG rename professor column in Course to professor_display_name

---

api/anubis/views/admin/auth.py
k8s/chart/templates/api.yml
k8s/chart/templates/pipeline-api.yml
k8s/chart/templates/theia.yml
k8s/chart/templates/web.yml
web/Dockerfile
web/src/Pages/Admin/Users.jsx

CLN summer cleaning 5

---

api/anubis/views/admin/courses.py
api/anubis/views/public/webhook.py
api/jobs/reaper.py
api/migrations/versions/2d4e34d460e8_rm_github_classrooms.py

FIX issues with github classroom removal

---

web/src/Pages/Admin/Course.jsx

FIX some minor issues with course management page

---

api/anubis/utils/lms/courses.py

FIX professor permission in anubis.utils.lms.courses.is_course_superuser

---

api/anubis/utils/k8s/theia.py
puller/main.go
theia/ide/admin/Dockerfile
theia/ide/devops/Dockerfile
theia/ide/jepst/Dockerfile
theia/ide/xv6/Dockerfile
theia/init/entrypoint.sh

FIX minor puller issues

---

api/anubis/views/public/ide.py
k8s/chart/templates/hpa.yml
k8s/chart/values.yaml

CHG tune hpas for student load

---

Makefile
api/.gitignore
api/anubis/utils/github/repos.py
api/anubis/utils/k8s/theia.py
api/anubis/utils/seed.py
api/anubis/views/admin/courses.py
api/anubis/views/admin/seed.py
api/anubis/views/public/repos.py
api/jobs/poller.py
k8s/chart/templates/api.yml
k8s/chart/templates/reaper-cron.yml
k8s/chart/templates/rpc.yml
theia/ide/admin/Dockerfile
theia/ide/admin/initialize-incluster.py
theia/ide/admin/supervisord.conf
web/src/Components/Admin/Course/CourseCard.jsx
web/src/Pages/Admin/Course.jsx
web/src/Pages/Public/Assignments.jsx

FIX bug fixes

---

k8s/chart/values.yaml
theia/ide/devops/Dockerfile

ADD devops env vars

---

api/anubis/utils/k8s/theia.py
k8s/chart/templates/network-policy.yml
theia/ide/devops/motd.txt
theia/proxy/index.js

ADD theia optional proxy

---

k8s/chart/templates/ingress.yml
k8s/chart/templates/theia.yml
k8s/prod/Makefile
k8s/prod/traefik-values.yaml
theia/proxy/index.js

ADD ide8000 domain for proxying to ide

---

api/anubis/utils/k8s/theia.py
api/anubis/utils/lms/theia.py
api/anubis/views/public/ide.py
api/jobs/poller.py
web/src/Components/Public/IDE/IDEDialog.jsx

ADD ide state to ide dialog

---

web/src/Pages/Admin/Assignment/Assignments.jsx

Fix Visibility row on admin assignments page.

CHG fix visibility row on assignments

---

old-web/src/Components/Navigation/Nav.jsx

Updated the button link(href) pointer

FIX the button href

---

theia/ide/theia-jepst/Dockerfile

Add ghc and swi-prolog, packages that were previously missing for ProgLang course

FIX add packages for ProgLang

---

theia/ide/theia-jepst/Dockerfile

Add yosys and unzip packages, which students will need

FIX add packages for CompArch

---

web/src/components/core/Questions/QuestionEditor.jsx
web/src/components/core/Questions/QuestionsCard.jsx

Ensure that the text editor correctly reads the response from
the question object and make it readonly in autograde result.
Fixes #347

FIX display issue of question responses in for the admin view

---

.github/workflows/codeql.yml

Modified from the template [here](https://github.com/github/codeql-action/blob/fd4dc5bf31bec2a626bf9a89113359953a1fba43/README.md).

ADD CodeQL code analysis workflow.

---

api/anubis/k8s/pvc/create.py
api/anubis/k8s/pvc/get.py
api/anubis/lms/courses.py
api/anubis/rpc/enqueue.py
api/anubis/views/admin/courses.py
web/src/components/core/Course/CourseCard.jsx
web/src/components/core/Users/BatchAddInput.jsx

ADD Batch Add Students

---

web/src/components/core/SubmissionTestExpanded/SubmissionTestExpanded.jsx

This prodcues more readable diffs.

CHG Reveal non-printable characters.

---

web/src/pages/core/public/Submissions/Submissions.jsx

Signed-off-by: Zixuan James Li <p359101898@gmail.com>

FIX translateSubmission to include the "accepted" prop.

---

web/src/components/core/Assignment/RepoCommandDialog.jsx
web/src/pages/core/public/Submissions/Submissions.jsx

A quick patch to evenly break people down into grading groups before we start with grading the next assignment.

FIX workload distribution of grading groups

---

api/anubis/jobs/reaper.py
api/anubis/lms/repos.py
api/anubis/views/admin/assignments.py
web/src/components/core/Assignment/RepoCommandDialog.jsx

TODO: change the clone script generator to include a version of links with commits.

ADD list repos with the commit to the latest submission.

---

web/src/components/forums/Comment/Comment.jsx
web/src/components/forums/CommentsList/CommentsList.jsx
web/src/components/forums/Post/Post.jsx
web/src/components/forums/Publisher/Publisher.jsx
web/src/pages/core/public/Forum/Forum.jsx

Forum edit comment
